# Parallel programming
# Assignment 2, exercise 4
# Group 55
# build an executable named bench
# To compile, first make a copy of the desired sorted_list variety
# and rename it sorted_class.h

all: .cpp
 	g++ -Wall -std=c++11 -pthread -O3 benchmark_example.cpp -o bench

clean:
	rm bench
